### ISSUE TITLE
不具合報告

### ISSUE THREAD

**Issue by Vassago-AF3** [Connect-a/ancl-loader#2]
不具合報告はこちらでよかったでしょうか？

3月に入ってからChromeとEdgeでエンクリローダーが使用できなくなってしまいました。
エラー履歴を確認すると“manifest_version”: 2の部分が黄色で表示されているので、素人なりに軽く調べてみたところ、マニフェストV3への移行が影響しているようです。

お忙しい中だとは思いますが、お手すきの際にご確認の程をよろしくお願い致します。

**Comment by Connect-a** [comment]
ChromeでもEdgeでもBraveでも動いてた。
以下を提供いただきたい。
- Chromeのバージョン
  - chrome://settings/help
- エラーの内容のコピペ
  - スクショでもよし
- どのレベルで使用できないのか
  - そもそも拡張機能を読み込めない
  - 起動しない
  - キャラクターが取得できない
  - ダウンロード失敗する

**Comment by Vassago-AF3** [comment]
・Chromeのバージョン
バージョン: 99.0.4844.51（Official Build） （64 ビット）
・エラーの内容
![スクリーンショット (570)](https://user-images.githubusercontent.com/101231468/157457458-cbb380d6-79eb-4fc5-8d5d-a32176383773.png)
・どのレベルで使用できないのか
拡張機能を読み込めてはいるが、エラーが発生しているので起動ができない状態です。

**Comment by Vassago-AF3** [comment]
何度もすみません。

Edgeの方はローダーを一度アンインストールして、再度取り込みを何回か繰り返してみたところ、ローダーが起動でき、データが取得できるようになりました。エラー自体は先程のスクショのものしか出ていないので、結局何だったのかは分かりませんが…。

**Comment by Vassago-AF3** [comment]
了解です。また何かありましたら連絡しますね。
今回はお騒がせしてすいませんでした。確認対応等、ありがとうございました！
