### ISSUE TITLE
chromeのバージョンアップによりポップアップの幅が最小になる

### ISSUE THREAD

**Issue by Phoebe-IX** [Connect-a/ancl-loader#4]
Connect-a様

お疲れ様です。まだここは見ていらっしゃるでしょうか…？

先日のedgeとchromeのアップデートよりローダーを起動してみても添付している画像のように紫と黒の部分が少し表示されるだけの状態となってしまいました。
ローダーの再インストールやPCの再起動なども試してみましたが効果がなかった為、ここで相談させていただきたく…。考えられる原因は何か分かりますでしょうか？

edgeとchromeのバージョンは以下の通りです。

・Microsoft Edge
バージョン 116.0.1938.54 (公式ビルド) (64 ビット)

・Chrome
バージョン: 116.0.5845.111（Official Build）（64 ビット）

![スクリーンショット ](https://github.com/Connect-a/ancl-loader/assets/143170168/a3beb107-7be7-447a-bc93-3ec4ee2c9283)

_Originally posted by @Phoebe-IX in https://github.com/Connect-a/ancl-loader/issues/2#issuecomment-1692965462_

**Comment by Connect-a** [comment]
たしかに。報告ありがとうございます。
ふるふるのサービス終了を追ってたりするんで、来月ごろの対応になるかと思われます。
とりあえず動かす方法をメモっときます。
※暫定回避策①
1. `chrome://extensions` を開いてIDを確認
1. `chrome-extension://{1. で確認したID}/popup.html#/` を開く
1. うごく
1. ブックマークに保存しとくのが良いかも

※暫定回避策②
1. 見えてる部分を右クリックして「検証」
1. htmlタグにwidthとheightを1000pxとか適当に設定
1. ひろがって見えるようになる

**Comment by Phoebe-IX** [comment]
了解です。
ご対応いただけるだけでもありがたいので、お手隙の際に進めていってもらえると大変助かります。

とりあえずは暫定回避策でまた表示できるようになりました。ありがとうございました…！

**Comment by Connect-a** [comment]
masterに直pushして修正をリリース。
https://github.com/Connect-a/ancl-loader/releases/tag/1.2.0
