### ISSUE TITLE
ダウンロード状況が「基本情報をダウンロード中」から進まない

### ISSUE THREAD

**Issue by qualia-11** [Connect-a/ancl-loader#5]
お疲れ様です。
去年の11月辺りからでしょうか、ダウンロードをするのですが、十数分程待っても「基本情報をダウンロード中」で止まってしまいます。自分でもソースを探ってたら、画像のようにハッシュ値が新たに追加されてて、キャラの画像などがソースに表示されない状態になっていました。
いつからこの仕様に変更されたのかも同時に気になるところですが...
目を通していただけると幸いです。
![スクリーンショット 2024-01-17 220223](https://github.com/Connect-a/ancl-loader/assets/156916035/de8cc464-3d14-48b5-a482-924b6d81ac7d)

**Comment by Connect-a** [comment]
報告ありがとうございます。確認しときます。
一次対応とかの話ではなさそうな気配。
メモ
- ビルドのたびに変わるハッシュ値なのか、ユーザーに割られるハッシュ値なのか。

**Comment by Connect-a** [comment]
めも
- プレイヤーが未完成だが、現在作成中のver2ならダウンロード出来ていそうな雰囲気ある。
  - 特殊ボイスを特定するための正規表現で少し手間取ってもいる。
- プレイヤー未完成状態かもだが来週末当たりにリリースしてみる。

**Comment by qualia-11** [comment]
対応お疲れ様です。
結局これはハッシュ値のファイル？の中に圧縮されてるのか、URLが取得不能になっているのかなのですかね...？

**Comment by Connect-a** [comment]
アルファ版をリリース  
https://github.com/Connect-a/ancl-loader/releases/tag/v2.0.0-alpha

**Comment by Connect-a** [comment]
ver2.1をリリース。おそらく修正完了。
https://github.com/Connect-a/ancl-loader/releases/tag/2.1.0
